"""
Legal/Compliance Department — Worker Agents
- LegalRouterAgent:           Classifies intent
- ContractReviewAgent:        Flags unusual clauses (uses RAG for uploaded contracts)
- ToSDrafterAgent:            Generates Terms of Service or Privacy Policy templates
- ComplianceChecklistAgent:   GDPR/CCPA/SOC2 checklist (calls Research via inter_dept)
- LegalSynthesizerAgent:      Combines outputs + MANDATORY NOT LEGAL ADVICE disclaimer
"""
import asyncio
from typing import Any, Dict, List

from pydantic import BaseModel, Field

from shared.base_agent import ProductionAgent, AgentOutput
from shared.tools import web_search

_DISCLAIMER = (
    "\n\n---\n"
    "WARNING: **NOT LEGAL ADVICE** — This output is generated by an AI system for "
    "informational purposes only. It does not constitute legal advice, create an "
    "attorney-client relationship, or substitute for consultation with a licensed attorney. "
    "Always consult a qualified legal professional before taking action."
)


class LegalRoute(BaseModel):
    required_agents: List[str] = Field(
        description="Agents to run. Options: contract_review, tos_draft, compliance_checklist."
    )
    reasoning: str


class LegalRouterAgent(ProductionAgent):
    name = "LegalRouterAgent"
    department = "legal"
    system_prompt = """You are a Legal Department Director. Classify the user legal request.
Options: contract_review (review/flag clauses), tos_draft (generate ToS or Privacy Policy),
compliance_checklist (GDPR/CCPA/SOC2 checklist). Select all that apply."""

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AgentOutput:
        try:
            result: LegalRoute = await self._ainvoke_structured(
                f"Legal request: {task}\n\nWhich agents are needed?", LegalRoute
            )
            return AgentOutput(
                agent_name=self.name, department=self.department, success=True,
                content=result.reasoning,
                metadata={"required_agents": result.required_agents}
            )
        except Exception as e:
            return AgentOutput(
                agent_name=self.name, department=self.department, success=False,
                content="", error=str(e),
                metadata={"required_agents": ["contract_review"]}
            )


class ContractReviewAgent(ProductionAgent):
    name = "ContractReviewAgent"
    department = "legal"
    system_prompt = """You are a Contract Attorney reviewing documents.
FLAG unusual or risky clauses: one-sided termination, excessive liability caps,
IP ownership traps, non-compete overreach, auto-renewal gotchas, governing law risks.
Quote the clause, explain the risk, suggest alternative language.
Do NOT give legal advice - flag issues only."""

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AgentOutput:
        context = context or {}
        uploaded_content = ""
        if context.get("user_id"):
            try:
                from shared.tools.rag_retrieval import rag_document_search
                uploaded_content = await asyncio.to_thread(
                    rag_document_search, query=task, user_id=context["user_id"], top_k=5
                )
            except Exception:
                pass
        contract_text = uploaded_content or task
        prompt = f"""Review for legal risks:\n\n{contract_text[:6000]}\n\nFlag all unusual clauses."""
        try:
            review = await self._ainvoke(prompt)
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=True, content=review, metadata={})
        except Exception as e:
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=False, content="", error=str(e), metadata={})


class ToSDrafterAgent(ProductionAgent):
    name = "ToSDrafterAgent"
    department = "legal"
    system_prompt = """You are a legal document drafter specializing in Terms of Service and Privacy Policies.
Generate comprehensive plain-language templates with all standard sections."""

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AgentOutput:
        prompt = f"Draft Terms of Service or Privacy Policy for: {task}\n\nInclude all standard sections."
        try:
            draft = await self._ainvoke(prompt)
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=True, content=draft, metadata={})
        except Exception as e:
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=False, content="", error=str(e), metadata={})


class ComplianceChecklistAgent(ProductionAgent):
    name = "ComplianceChecklistAgent"
    department = "legal"
    system_prompt = """You are a Compliance Officer specializing in GDPR, CCPA, and SOC2.
Generate a practical compliance checklist. For each item: requirement, action needed, risk of non-compliance."""

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AgentOutput:
        try:
            from shared.inter_dept import call_research_dept
            reg_info = await call_research_dept(
                task=f"Current GDPR CCPA SOC2 compliance requirements for: {task}",
                api_keys=(context or {}).get("api_keys"),
                selected_model=(context or {}).get("selected_model"),
            )
        except Exception:
            reg_info = ""
        prompt = f"Generate compliance checklist for: {task}\n\nContext: {reg_info[:2000]}"
        try:
            checklist = await self._ainvoke(prompt)
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=True, content=checklist, metadata={})
        except Exception as e:
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=False, content="", error=str(e), metadata={})


class LegalSynthesizerAgent(ProductionAgent):
    name = "LegalSynthesizerAgent"
    department = "legal"
    system_prompt = "You are a Legal Summary specialist. Combine all legal analysis clearly. Always add the NOT LEGAL ADVICE disclaimer."

    async def execute(self, task: str, context: Dict[str, Any] = None) -> AgentOutput:
        context = context or {}
        parts = [f"# Legal Analysis\n"]
        if context.get("contract_review"):
            parts.append(f"## Contract Review\n{context['contract_review']}\n")
        if context.get("tos_draft"):
            parts.append(f"## Document Draft\n{context['tos_draft']}\n")
        if context.get("compliance_checklist"):
            parts.append(f"## Compliance Checklist\n{context['compliance_checklist']}\n")
        combined = "\n".join(parts)
        try:
            synthesis = await self._ainvoke(f"Synthesize clearly:\n\n{combined[:5000]}")
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=True, content=synthesis + _DISCLAIMER, metadata={})
        except Exception as e:
            return AgentOutput(agent_name=self.name, department=self.department,
                               success=True, content=combined + _DISCLAIMER, error=str(e), metadata={})
